### PR TITLE
Create gcloud configuration.

### PR DESCRIPTION
**Pull request by tmatsuo**

### CODE REVIEW

**Comment by bshaffer** [comment]
Looks like this is erroring because in the latest version of `php-cs-fixer` they've renamed `--config-file` to `--config`

**Comment by bshaffer** [comment]
hmm, also it seems like if the `.php_cs` file is present, it is automatically loaded.

**Comment by tmatsuo** [comment]
The format for `.php_cs` also changed. I updated it too.

**Comment by tmatsuo** [comment]
The test is passing, can I merge this?

**Comment by bshaffer** [comment]
LGRTM!!!

**Pull request merged**
