### PR TITLE
feat(functions): add system test trait

### PR DESCRIPTION
**Pull request by grayside**
Adds a simple trait to facilitate system tests for functions.

### CODE REVIEW

**Comment by bshaffer** [comment]
It's not super clear to me what this does that the previous PR (`CloudFunctionsDeploymentTrait`) doesn't do

**Comment by grayside** [comment]
CloudFunctionsDeploymentTrait deploys the function then deletes it.
This runs the function locally with the Functions Framework.

**Comment by bshaffer** [comment]
Could you add that in the class comment for the Trait, and/or rename it to `CloudFunctionsLocalTestTrait`?

**Review by bshaffer — APPROVED** [review]

**Comment by grayside** [comment]
Both done.

**Pull request merged**
